
- group: Essential
  nodes: ["uavcan_to_ros_bridge_node", "ros_to_uavcan_bridge_node", "stim_imu_driver", "press_to_depth", "ekf_loc_local"]
  max_load:
  max_ram:
  on_kill: abort

- group: Default
  nodes: ".*"
  max_load: 0.5
  max_ram: 2.0
  on_max: restart
  max_restarts: 10
  on_kill:
